name: CI

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  flutter_test:
    name: Run Flutter tests and analyze
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # Recommended for Android builds
          java-version: '11'

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Flutter doctor
        run: flutter doctor

      - name: Get dependencies
        run: flutter pub get

      - name: Run analyzer
        run: flutter analyze

      - name: Run tests
        run: flutter test

  build_ios:
    name: Build Flutter (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Flutter doctor
        run: flutter doctor

      - name: Get dependencies
        run: flutter pub get

      - name: Clean build files
        run: flutter clean

      - name: Build iOS app
        run: flutter build ios

  build_appbundle:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Flutter doctor
        run: flutter doctor

      - name: Get dependencies
        run: flutter pub get

      - name: Clean build files
        run: flutter clean

      - name: Build Android AppBundle
        run: flutter build appbundle
